start = root 
root = element root {title, author, stan+, source}

title = element title {text}
author = element author {text}

stan = element stan {key, slt+}
key = attribute key {xsd:integer}
slt = element slt {(total | line | rhy)+}
line = element line {id?, key+, rhy+}
id = attribute id {"lnum"}
rhy = element rhy {sch, text}
sch = attribute sch {capitalString}
total = attribute total {xsd:integer}
source = element source {text}

capitalString = xsd:string {pattern = "[A-Z]"}
# a range for only capital letters. regualar expressions help to constraign the text


